name: Check and build packages

on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Python and pip
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
        
      - name: Install ubuntu dependencies
        run: |
          sudo apt update
          sudo apt install -y secure-delete neofetch libarchive-tools s3fs

      - name: Prepare the machine
        run: |
          set -e
          neofetch
          
          echo "${{secrets.S3_ACCESS_KEY_ID}}:${{secrets.S3_SECRET_ACCESS_KEY}}" > ~/.passwd-s3fs
          chmod 600 ~/.passwd-s3fs
          mkdir -p ~/s3root
          s3fs -o passwd_file=~/.passwd-s3fs,url=${{secrets.S3_BUCKET_URL}} ${{vars.S3_BUCKET_NAME}} ~/s3root
          ln -s ~/s3root/${{vars.REPO_NAME}} ~/repo
          ls -lahH ~/repo

          cat <<EOF >> ~/gpg_privatekey.asc
          ${{secrets.GPG_PRIVATE_KEY}}
          EOF
          chmod 600 ~/gpg_privatekey.asc
          gpg --import ~/gpg_privatekey.asc
          srm ~/gpg_privatekey.asc
          
          pip install -r requirements.txt
          
      - name: Run the builder
        env:
          REPO_NAME: ${{vars.REPO_NAME}}
          MANTAINER_NAME: ${{vars.MANTAINER_NAME}}
          MANTAINER_EMAIL: ${{vars.MANTAINER_EMAIL}}
          CUSTOM_REPO_NAME: ${{vars.CUSTOM_REPO_NAME}}
          CUSTOM_REPO_KEYID: ${{vars.CUSTOM_REPO_KEYID}}
          CUSTOM_REPO_URL: ${{secrets.CUSTOM_REPO_URL}}
        run: |
          python3 src/main.py
      
      - name: Cleanup
        run: |
          umount ~/s3root
          srm -r ~/.gnupg
          srm -r ~/.passwd-s3fs

