name: Check for outdated packages

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  check-for-outdated-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install ubuntu dependencies
        run: |
          sudo apt update
          sudo apt install -y sshfs secure-delete
      
      - name: Prepare the machine
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          cat <<EOF >> ~/.ssh/id_ed25519
          ${{secrets.SSH_PRIVATE_KEY}}
          EOF
          chmod 600 ~/.ssh/id_ed25519
          echo ${{secrets.SSH_KNOWN_HOSTS}} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          pip install -r src/requirements.txt

          cat <<EOF >> ~/gpg_privatekey.asc
          ${{secrets.GPG_PRIVATE_KEY}}
          EOF
          chmod 600 ~/gpg_privatekey.asc
          gpg --import ~/gpg_privatekey.asc
          srm ~/gpg_privatekey.asc

          mkdir -p ~/repo
          sshfs -p ${{secrets.SSH_REMOTE_PORT}} ${{secrets.SSH_REMOTE_USER}}@${{secrets.SSH_REMOTE_HOST}}:/${{secrets.SSH_REMOTE_PATH}} ~/repo
          ls -la ~/repo

      - name: Run the builder
        run: |
          python3 src/main.py
